// Code generated by tygo. DO NOT EDIT.

//////////
// source: ai.go

export interface AiRequest {
  topic: string;
}
export interface AiResponse {
  posts: {
    content: string;
  }[];
}

//////////
// source: articles.go

export interface Articles {
  Model: any /* gorm.Model */;
  ID: number /* uint */;
  Title: string;
  Short_Desc?: string;
  Content?: string;
  Tags?: string;
  CreatedAt: string /* RFC3339 */;
  UpdatedAt: string /* RFC3339 */;
  DeletedAt?: string /* RFC3339 */;
}
export interface Articles_Select {
  ID: number /* uint */;
  Title: string;
  Short_Desc: string;
  Tags: string;
  CreatedAt: string /* RFC3339 */;
  UpdatedAt: string /* RFC3339 */;
}

//////////
// source: connections.go

export interface Connections {
  Model: any /* gorm.Model */;
  ID: number /* uint */;
  UserId: string;
  Name: string;
  Username: string;
  ConnectionName: string;
  ConnectionId: string;
  AccessToken: string;
  RefreshToken: string;
  MetaData: string;
  ProfileImage: string;
  Timezone: string;
  CreatedAt: string /* RFC3339 */;
  UpdatedAt: string /* RFC3339 */;
  DeletedAt?: string /* RFC3339 */;
}
export interface Connections_Select {
  ID: number /* uint */;
  UserId: string;
  Name: string;
  Username: string;
  ConnectionName: string;
  ConnectionId: string;
  AccessToken: string;
  RefreshToken: string;
  MetaData: string;
  ProfileImage: string;
  Timezone: string;
  CreatedAt: string /* RFC3339 */;
  UpdatedAt: string /* RFC3339 */;
}

//////////
// source: pagination.go

export interface Pagination {
  Page: number /* int */;
  PrevPage: number /* int */;
  NextPage: number /* int */;
  Limit: number /* int */;
  Offset: number /* int */;
  TotalPage: number /* int */;
  TotalRow: number /* int64 */;
}

//////////
// source: posts.go

export interface Posts {
  Model: any /* gorm.Model */;
  ID: number /* uint */;
  UserId: string;
  Title: string;
  Content: string;
  PublishAt: string;
  PublishStatus: string;
  Medias: string;
  Tags: string;
  CreatedAt: string /* RFC3339 */;
  UpdatedAt: string /* RFC3339 */;
  DeletedAt?: string /* RFC3339 */;
}

//////////
// source: social-posts.go

export interface SocialPosts {
  Model: any /* gorm.Model */;
  ID: number /* uint */;
  ConnectionId: string;
  UserId: string;
  Title: string;
  Description: string;
  Link: string;
  Medias: string;
  Type: string;
  PublishAt: string;
  Status: string;
  Logs: string;
  PublishedPostId: string;
  CreatedAt: string /* RFC3339 */;
  UpdatedAt: string /* RFC3339 */;
  DeletedAt?: string /* RFC3339 */;
}

//////////
// source: user.go

export interface Users {
  Model: any /* gorm.Model */;
  ID: number /* uint */;
  Name: string;
  Username: string;
  Email: string;
  Password: string;
  Token: string;
  Provider: string;
  UserId: string;
  AvatarURL: string;
  CreatedAt: string /* RFC3339 */;
  UpdatedAt: string /* RFC3339 */;
  DeletedAt?: string /* RFC3339 */;
}
export interface Users_Select {
  ID: number /* uint */;
  Name: string;
  Username: string;
  Email: string;
  Token: string;
  Provider: string;
  UserId: string;
  CreatedAt: string /* RFC3339 */;
  UpdatedAt: string /* RFC3339 */;
}
export interface SignUpFormRequest {
  Name: string;
  Username: string;
  Email: string;
  Password: string;
}
export interface SignUpResponse {
  token: string;
}
export interface SignInFormRequest {
  Email: string;
  Password: string;
}
export interface SignInResponse {
  token: string;
}
